name: Build and test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: User_123
        ports:
        - 3306:3306
    
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: setup redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'
    
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: '11' # The JDK version to make available on the path.
        java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
        architecture: x64 # (x64 or x86) - defaults to x64
    
    - name: setup zookeeper
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://downloads.apache.org/zookeeper/zookeeper-3.6.2/apache-zookeeper-3.6.2-bin.tar.gz
        tar -xzf apache-zookeeper-3.6.2-bin.tar.gz
        cd apache-zookeeper-3.6.2-bin/bin && sudo ./zkServer.sh start
        sudo netstat plnto
        sudo ps aux

    - name: build and test
      uses: cedrickring/golang-action@1.6.0
      env:
        PROJECT_PATH: "./cypress"
        GO111MODULE: "on"