name: Build and test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: checkout source
      uses: actions/checkout@v2

    - name: setup redis
      uses: zhulik/redis-action@1.1.0
      with:
        redis version: '5'

    - name: setup mysql
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
        mysql root password: User_123
    
    - name: setup zookeeper
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://downloads.apache.org/zookeeper/zookeeper-3.6.2/apache-zookeeper-3.6.2-bin.tar.gz
        tar -xvzf apache-zookeeper-3.6.2-bin.tar.gz
        apache-zookeeper-3.6.2-bin/bin/zkServer.sh start

    - name: build and test
      uses: cedrickring/golang-action@1.6.0
      env:
        PROJECT_PATH: "./cypress"
        GO111MODULE: "on"